### ISSUE TITLE
How to add the plugin? [iOS]

### ISSUE THREAD

**Issue by matrixreal** [tomitank/cordova-admob-tomitank#1]
Hello,
Thanks for the great work
Can you tell us how to add the plugin?
What about consent form?

**Comment by tomitank** [comment]
Hi! Please read admob-plus plugin readme, there is a admob-consent plugin as wellAz iPhone-omról küldve2023. máj. 27. dátummal, 15:48 időpontban MATRIX.REAL ***@***.***> írta:﻿
Hello,
Thanks for the great work
Can you tell us how to add the plugin?
What about consent form?
